#!/usr/bin/env node
/**
 * Image processing pipeline (HANDOVER §6.3).
 *
 * Input : assets/photos-src/{slot}.(jpg|jpeg|png|webp|tif|tiff)
 *         assets/photos-src/{slot}.credit.json  → {title, author, license, sourceUrl}
 * Output: public/images/{slot}/{slot}-{width}.{avif|webp|jpg}
 *         content/photos.generated.json  (registry consumed by lib/photos.ts)
 *         content/credits.md             (human-readable credits list)
 *
 * Crop to the slot ratio with sharp's attention strategy, export
 * AVIF (~q50) / WebP (~q72) / JPEG, widths 480/960/1600/2400 (capped at
 * source width), plus a base64 LQIP blur placeholder.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = path.resolve(import.meta.dirname, '..');
const SRC_DIR = path.join(ROOT, 'assets/photos-src');
const OUT_DIR = path.join(ROOT, 'public/images');
const WIDTHS = [480, 960, 1600, 2400];

const manifest = JSON.parse(
  await fs.readFile(path.join(ROOT, 'content/photos.manifest.json'), 'utf8'),
);
const slotById = Object.fromEntries(manifest.slots.map((s) => [s.id, s]));

let sources = [];
try {
  sources = (await fs.readdir(SRC_DIR)).filter((f) => /\.(jpe?g|png|webp|tiff?)$/i.test(f));
} catch {
  console.log(`No ${path.relative(ROOT, SRC_DIR)}/ yet — nothing to process.`);
  console.log('Run npm run photos:source first, review candidates, copy picks there.');
  process.exit(0);
}

const registry = { note: 'Generated by scripts/build-images.mjs — do not edit by hand.', images: {}, credits: [] };

for (const file of sources) {
  const slotId = path.parse(file).name;
  const slot = slotById[slotId];
  if (!slot) {
    console.warn(`! ${file}: no slot "${slotId}" in manifest — skipped`);
    continue;
  }

  const [rw, rh] = slot.ratio.split(':').map(Number);
  const aspect = rw / rh;
  const input = sharp(path.join(SRC_DIR, file), { failOn: 'none' }).rotate();
  const meta = await input.metadata();
  const slotOut = path.join(OUT_DIR, slotId);
  await fs.mkdir(slotOut, { recursive: true });

  const widths = WIDTHS.filter((w) => w <= (meta.width ?? 0) * 1.05);
  if (widths.length === 0) widths.push(Math.min(meta.width ?? 480, 480));

  for (const w of widths) {
    const h = Math.round(w / aspect);
    const resized = input.clone().resize(w, h, { fit: 'cover', position: sharp.strategy.attention });
    await resized.clone().avif({ quality: 50, effort: 4 }).toFile(path.join(slotOut, `${slotId}-${w}.avif`));
    await resized.clone().webp({ quality: 72 }).toFile(path.join(slotOut, `${slotId}-${w}.webp`));
    await resized.clone().jpeg({ quality: 78, progressive: true, mozjpeg: true }).toFile(path.join(slotOut, `${slotId}-${w}.jpg`));
  }

  const lqipBuf = await input
    .clone()
    .resize(24, Math.round(24 / aspect), { fit: 'cover' })
    .webp({ quality: 25 })
    .toBuffer();

  registry.images[slotId] = {
    widths,
    aspect: Number(aspect.toFixed(4)),
    lqip: `data:image/webp;base64,${lqipBuf.toString('base64')}`,
    formats: ['avif', 'webp', 'jpg'],
  };

  try {
    const credit = JSON.parse(
      await fs.readFile(path.join(SRC_DIR, `${slotId}.credit.json`), 'utf8'),
    );
    registry.credits.push({ slot: slotId, ...credit });
  } catch {
    console.warn(`! ${slotId}: no credit sidecar (${slotId}.credit.json) — add one before launch`);
  }

  console.log(`✓ ${slotId} → ${widths.join('/')}px (avif+webp+jpg, lqip)`);
}

registry.credits.sort((a, b) => a.slot.localeCompare(b.slot));
await fs.writeFile(
  path.join(ROOT, 'content/photos.generated.json'),
  JSON.stringify(registry, null, 2) + '\n',
);

const creditsMd = [
  '# Фотографии: авторы и лицензии',
  '',
  '_Generated by scripts/build-images.mjs — surfaced on the site at `/credits`._',
  '',
  ...(registry.credits.length === 0
    ? ['_No credited images yet._']
    : registry.credits.map(
        (c) => `- **${c.slot}** — «${c.title}» · ${c.author} · ${c.license} · ${c.sourceUrl}`,
      )),
  '',
].join('\n');
await fs.writeFile(path.join(ROOT, 'content/credits.md'), creditsMd);

console.log(`\nRegistry: content/photos.generated.json (${Object.keys(registry.images).length} slots)`);
console.log('Credits : content/credits.md');
